name: Publish to Artifact Repository

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'

      - name: Publish to Artifact Repository
        run: |
          echo $CREDENTIALS >> tech_bucket_key.json && \
          mvn deploy -DskipTests
        env:
          CREDENTIALS: ${{ secrets.TECH_ARTIFACTS_BUCKET_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS: tech_bucket_key.json
